from bogosort import bogosort
from bozosort import bozosort
from bubblesort import bubblesort
from cocktailsort import cocktailsort
from gnomesort import gnomesort
from insertionsort import insertionsort
from mergesort import mergesort
from quicksort import quicksort
from selectionsort import selectionsort
